###Read all users
GET http://localhost:3000/user-api/users
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNoQGdtYWlsLmNvbSIsImlhdCI6MTc3MzMzNjU1MSwiZXhwIjoxNzczMzQwMTUxfQ.VQSNqIVxOMR5Yeh1FKpfJZ-bpBkwmHp4l2axVwOwziM

### Read a user by id
GET http://localhost:3000/user-api/users/69b2f1c50173e99336e4bdf1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNoQGdtYWlsLmNvbSIsImlhdCI6MTc3MzMzNjU1MSwiZXhwIjoxNzczMzQwMTUxfQ.VQSNqIVxOMR5Yeh1FKpfJZ-bpBkwmHp4l2axVwOwziM

### Create new user
POST http://localhost:3000/user-api/users
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNoQGdtYWlsLmNvbSIsImlhdCI6MTc3MzMzNjU1MSwiZXhwIjoxNzczMzQwMTUxfQ.VQSNqIVxOMR5Yeh1FKpfJZ-bpBkwmHp4l2axVwOwziM

{
    "username":"krish",
    "password":"bannu",
    "email":"krish@gmail.com",
    "age":25
    
}


### 
PUT http://localhost:3000/user-api/users/69b2f0e6b133e7f2d5559d0a
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNoQGdtYWlsLmNvbSIsImlhdCI6MTc3MzMzNjU1MSwiZXhwIjoxNzczMzQwMTUxfQ.VQSNqIVxOMR5Yeh1FKpfJZ-bpBkwmHp4l2axVwOwziM

{  
    "username":"bannu",
    "password":"bannu",
    "email":"abcd@gmail.com",
    "age":25   
}

###user login
POST http://localhost:3000/user-api/auth
Content-Type: application/json

{
    "email":"krish@gmail.com",
    "password":"bannu"
}

###delete user
DELETE http://localhost:3000/user-api/users/69b2f1c50173e99336e4bdf1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtyaXNoQGdtYWlsLmNvbSIsImlhdCI6MTc3MzMzNjU1MSwiZXhwIjoxNzczMzQwMTUxfQ.VQSNqIVxOMR5Yeh1FKpfJZ-bpBkwmHp4l2axVwOwziM
